---
label: Config
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: subtitle
  type: text
  config:
    required: false
  label: Subtitle
- name: description
  type: text
  config:
    required: false
  label: Description
- name: featuredImage
  type: file
  config:
    maxSize: 64
  label: Icon
- name: links
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: false
    label: Name
  - name: url
    type: text
    config:
      required: false
    label: Url
  - name: icon
    type: text
    config:
      required: false
    label: Icon
  config:
    min: 
    max: 
    labelField: 
  label: Links
pages:
- src/core/config.json
- src/projects/geotiles.md
